name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build:
    name: Build the NoIP Docker image
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build image
        run: |
          docker build -t madduci/docker-noip:latest . 